# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Xylo Sweden
email: info@xylosweden.se
description: >- # this means to ignore newlines until "baseurl:"
  We make businesses thrive in the new green economy.
  We are not just consultants – we are collaborators,
  providing the knowledge, resources, and guidance you
  need to effect real change.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://test1.xylosweden.se" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "default"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-sitemap

repository: "xylosweden/xylosweden.github.io"
  #teaser: /assets/images/500x300.png
logo: "/assets/images/xylo-logo.png"
masthead_title: " "

business: "Lövgatan 49, 16932 Solna, Org.no 559399-2604"
search: true
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      share: true
      related: true

footer:
  links:
    - label: "Home"
      url: /
    - label: "Services"
      url: /services/
    - label: "About"
      url: /about/
    - label: "Our blog"
      url: /blog/
    - label: "Contact us"
      url: /contact-us/
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/company/xylo-sweden"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#
